# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, request_id: int=None, request_url: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param request_id: The request_id of this InlineResponse200.  # noqa: E501
        :type request_id: int
        :param request_url: The request_url of this InlineResponse200.  # noqa: E501
        :type request_url: str
        """
        self.swagger_types = {
            'request_id': int,
            'request_url': str
        }

        self.attribute_map = {
            'request_id': 'requestId',
            'request_url': 'requestURL'
        }
        self._request_id = request_id
        self._request_url = request_url

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self) -> int:
        """Gets the request_id of this InlineResponse200.


        :return: The request_id of this InlineResponse200.
        :rtype: int
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: int):
        """Sets the request_id of this InlineResponse200.


        :param request_id: The request_id of this InlineResponse200.
        :type request_id: int
        """

        self._request_id = request_id

    @property
    def request_url(self) -> str:
        """Gets the request_url of this InlineResponse200.


        :return: The request_url of this InlineResponse200.
        :rtype: str
        """
        return self._request_url

    @request_url.setter
    def request_url(self, request_url: str):
        """Sets the request_url of this InlineResponse200.


        :param request_url: The request_url of this InlineResponse200.
        :type request_url: str
        """

        self._request_url = request_url
