# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoExportBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, request_id: int=None):  # noqa: E501
        """IoExportBody - a model defined in Swagger

        :param request_id: The request_id of this IoExportBody.  # noqa: E501
        :type request_id: int
        """
        self.swagger_types = {
            'request_id': int
        }

        self.attribute_map = {
            'request_id': 'requestId'
        }
        self._request_id = request_id

    @classmethod
    def from_dict(cls, dikt) -> 'IoExportBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The io_export_body of this IoExportBody.  # noqa: E501
        :rtype: IoExportBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self) -> int:
        """Gets the request_id of this IoExportBody.


        :return: The request_id of this IoExportBody.
        :rtype: int
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: int):
        """Sets the request_id of this IoExportBody.


        :param request_id: The request_id of this IoExportBody.
        :type request_id: int
        """

        self._request_id = request_id
