# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ListInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, directory: object=None):  # noqa: E501
        """ListInner - a model defined in Swagger

        :param directory: The directory of this ListInner.  # noqa: E501
        :type directory: object
        """
        self.swagger_types = {
            'directory': object
        }

        self.attribute_map = {
            'directory': 'directory'
        }
        self._directory = directory

    @classmethod
    def from_dict(cls, dikt) -> 'ListInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The List_inner of this ListInner.  # noqa: E501
        :rtype: ListInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def directory(self) -> object:
        """Gets the directory of this ListInner.


        :return: The directory of this ListInner.
        :rtype: object
        """
        return self._directory

    @directory.setter
    def directory(self, directory: object):
        """Sets the directory of this ListInner.


        :param directory: The directory of this ListInner.
        :type directory: object
        """

        self._directory = directory
