# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.project_create_v3 import ProjectCreateV3  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class ProjectCreateResponseV3(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None, ethics_vote: str=None, expected_end_time: str=None, id: int=None, creation_time: str=None):  # noqa: E501
        """ProjectCreateResponseV3 - a model defined in Swagger

        :param title: The title of this ProjectCreateResponseV3.  # noqa: E501
        :type title: str
        :param description: The description of this ProjectCreateResponseV3.  # noqa: E501
        :type description: str
        :param ethics_vote: The ethics_vote of this ProjectCreateResponseV3.  # noqa: E501
        :type ethics_vote: str
        :param expected_end_time: The expected_end_time of this ProjectCreateResponseV3.  # noqa: E501
        :type expected_end_time: str
        :param id: The id of this ProjectCreateResponseV3.  # noqa: E501
        :type id: int
        :param creation_time: The creation_time of this ProjectCreateResponseV3.  # noqa: E501
        :type creation_time: str
        """
        self.swagger_types = {
            'title': str,
            'description': str,
            'ethics_vote': str,
            'expected_end_time': str,
            'id': int,
            'creation_time': str
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            'ethics_vote': 'ethicsVote',
            'expected_end_time': 'expectedEndTime',
            'id': 'id',
            'creation_time': 'creationTime'
        }
        self._title = title
        self._description = description
        self._ethics_vote = ethics_vote
        self._expected_end_time = expected_end_time
        self._id = id
        self._creation_time = creation_time

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectCreateResponseV3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProjectCreateResponseV3 of this ProjectCreateResponseV3.  # noqa: E501
        :rtype: ProjectCreateResponseV3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this ProjectCreateResponseV3.


        :return: The title of this ProjectCreateResponseV3.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ProjectCreateResponseV3.


        :param title: The title of this ProjectCreateResponseV3.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this ProjectCreateResponseV3.


        :return: The description of this ProjectCreateResponseV3.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProjectCreateResponseV3.


        :param description: The description of this ProjectCreateResponseV3.
        :type description: str
        """

        self._description = description

    @property
    def ethics_vote(self) -> str:
        """Gets the ethics_vote of this ProjectCreateResponseV3.


        :return: The ethics_vote of this ProjectCreateResponseV3.
        :rtype: str
        """
        return self._ethics_vote

    @ethics_vote.setter
    def ethics_vote(self, ethics_vote: str):
        """Sets the ethics_vote of this ProjectCreateResponseV3.


        :param ethics_vote: The ethics_vote of this ProjectCreateResponseV3.
        :type ethics_vote: str
        """

        self._ethics_vote = ethics_vote

    @property
    def expected_end_time(self) -> str:
        """Gets the expected_end_time of this ProjectCreateResponseV3.

        date/time when project will probably end  # noqa: E501

        :return: The expected_end_time of this ProjectCreateResponseV3.
        :rtype: str
        """
        return self._expected_end_time

    @expected_end_time.setter
    def expected_end_time(self, expected_end_time: str):
        """Sets the expected_end_time of this ProjectCreateResponseV3.

        date/time when project will probably end  # noqa: E501

        :param expected_end_time: The expected_end_time of this ProjectCreateResponseV3.
        :type expected_end_time: str
        """

        self._expected_end_time = expected_end_time

    @property
    def id(self) -> int:
        """Gets the id of this ProjectCreateResponseV3.


        :return: The id of this ProjectCreateResponseV3.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ProjectCreateResponseV3.


        :param id: The id of this ProjectCreateResponseV3.
        :type id: int
        """

        self._id = id

    @property
    def creation_time(self) -> str:
        """Gets the creation_time of this ProjectCreateResponseV3.

        date/time when project was created  # noqa: E501

        :return: The creation_time of this ProjectCreateResponseV3.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time: str):
        """Sets the creation_time of this ProjectCreateResponseV3.

        date/time when project was created  # noqa: E501

        :param creation_time: The creation_time of this ProjectCreateResponseV3.
        :type creation_time: str
        """

        self._creation_time = creation_time
