# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QueryCollections(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, biobank_id: str=None, collection_id: str=None):  # noqa: E501
        """QueryCollections - a model defined in Swagger

        :param biobank_id: The biobank_id of this QueryCollections.  # noqa: E501
        :type biobank_id: str
        :param collection_id: The collection_id of this QueryCollections.  # noqa: E501
        :type collection_id: str
        """
        self.swagger_types = {
            'biobank_id': str,
            'collection_id': str
        }

        self.attribute_map = {
            'biobank_id': 'biobankId',
            'collection_id': 'collectionId'
        }
        self._biobank_id = biobank_id
        self._collection_id = collection_id

    @classmethod
    def from_dict(cls, dikt) -> 'QueryCollections':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Query_collections of this QueryCollections.  # noqa: E501
        :rtype: QueryCollections
        """
        return util.deserialize_model(dikt, cls)

    @property
    def biobank_id(self) -> str:
        """Gets the biobank_id of this QueryCollections.


        :return: The biobank_id of this QueryCollections.
        :rtype: str
        """
        return self._biobank_id

    @biobank_id.setter
    def biobank_id(self, biobank_id: str):
        """Sets the biobank_id of this QueryCollections.


        :param biobank_id: The biobank_id of this QueryCollections.
        :type biobank_id: str
        """

        self._biobank_id = biobank_id

    @property
    def collection_id(self) -> str:
        """Gets the collection_id of this QueryCollections.


        :return: The collection_id of this QueryCollections.
        :rtype: str
        """
        return self._collection_id

    @collection_id.setter
    def collection_id(self, collection_id: str):
        """Sets the collection_id of this QueryCollections.


        :param collection_id: The collection_id of this QueryCollections.
        :type collection_id: str
        """

        self._collection_id = collection_id
