# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QueryCreateResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, redirect_uri: str=None):  # noqa: E501
        """QueryCreateResponse - a model defined in Swagger

        :param redirect_uri: The redirect_uri of this QueryCreateResponse.  # noqa: E501
        :type redirect_uri: str
        """
        self.swagger_types = {
            'redirect_uri': str
        }

        self.attribute_map = {
            'redirect_uri': 'redirect_uri'
        }
        self._redirect_uri = redirect_uri

    @classmethod
    def from_dict(cls, dikt) -> 'QueryCreateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryCreateResponse of this QueryCreateResponse.  # noqa: E501
        :rtype: QueryCreateResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def redirect_uri(self) -> str:
        """Gets the redirect_uri of this QueryCreateResponse.


        :return: The redirect_uri of this QueryCreateResponse.
        :rtype: str
        """
        return self._redirect_uri

    @redirect_uri.setter
    def redirect_uri(self, redirect_uri: str):
        """Sets the redirect_uri of this QueryCreateResponse.


        :param redirect_uri: The redirect_uri of this QueryCreateResponse.
        :type redirect_uri: str
        """

        self._redirect_uri = redirect_uri
