# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.query_collections import QueryCollections  # noqa: F401,E501
from swagger_server.models.query_create_v3 import QueryCreateV3  # noqa: F401,E501
from swagger_server import util


class QueryV3(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, human_readable: str=None, collections: List[QueryCollections]=None, id: int=None):  # noqa: E501
        """QueryV3 - a model defined in Swagger

        :param url: The url of this QueryV3.  # noqa: E501
        :type url: str
        :param human_readable: The human_readable of this QueryV3.  # noqa: E501
        :type human_readable: str
        :param collections: The collections of this QueryV3.  # noqa: E501
        :type collections: List[QueryCollections]
        :param id: The id of this QueryV3.  # noqa: E501
        :type id: int
        """
        self.swagger_types = {
            'url': str,
            'human_readable': str,
            'collections': List[QueryCollections],
            'id': int
        }

        self.attribute_map = {
            'url': 'url',
            'human_readable': 'humanReadable',
            'collections': 'collections',
            'id': 'id'
        }
        self._url = url
        self._human_readable = human_readable
        self._collections = collections
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'QueryV3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryV3 of this QueryV3.  # noqa: E501
        :rtype: QueryV3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this QueryV3.


        :return: The url of this QueryV3.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this QueryV3.


        :param url: The url of this QueryV3.
        :type url: str
        """

        self._url = url

    @property
    def human_readable(self) -> str:
        """Gets the human_readable of this QueryV3.


        :return: The human_readable of this QueryV3.
        :rtype: str
        """
        return self._human_readable

    @human_readable.setter
    def human_readable(self, human_readable: str):
        """Sets the human_readable of this QueryV3.


        :param human_readable: The human_readable of this QueryV3.
        :type human_readable: str
        """

        self._human_readable = human_readable

    @property
    def collections(self) -> List[QueryCollections]:
        """Gets the collections of this QueryV3.


        :return: The collections of this QueryV3.
        :rtype: List[QueryCollections]
        """
        return self._collections

    @collections.setter
    def collections(self, collections: List[QueryCollections]):
        """Sets the collections of this QueryV3.


        :param collections: The collections of this QueryV3.
        :type collections: List[QueryCollections]
        """

        self._collections = collections

    @property
    def id(self) -> int:
        """Gets the id of this QueryV3.

        Id of the query generated  # noqa: E501

        :return: The id of this QueryV3.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this QueryV3.

        Id of the query generated  # noqa: E501

        :param id: The id of this QueryV3.
        :type id: int
        """

        self._id = id
