# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.query_v3 import QueryV3  # noqa: F401,E501
from swagger_server import util


class QueryResponseV3(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, redirect_url: str=None):  # noqa: E501
        """QueryResponseV3 - a model defined in Swagger

        :param id: The id of this QueryResponseV3.  # noqa: E501
        :type id: int
        :param redirect_url: The redirect_url of this QueryResponseV3.  # noqa: E501
        :type redirect_url: str
        """
        self.swagger_types = {
            'id': int,
            'redirect_url': str
        }

        self.attribute_map = {
            'id': 'id',
            'redirect_url': 'redirectUrl'
        }
        self._id = id
        self._redirect_url = redirect_url

    @classmethod
    def from_dict(cls, dikt) -> 'QueryResponseV3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryResponseV3 of this QueryResponseV3.  # noqa: E501
        :rtype: QueryResponseV3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this QueryResponseV3.

        Id of the query generated  # noqa: E501

        :return: The id of this QueryResponseV3.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this QueryResponseV3.

        Id of the query generated  # noqa: E501

        :param id: The id of this QueryResponseV3.
        :type id: int
        """

        self._id = id

    @property
    def redirect_url(self) -> str:
        """Gets the redirect_url of this QueryResponseV3.


        :return: The redirect_url of this QueryResponseV3.
        :rtype: str
        """
        return self._redirect_url

    @redirect_url.setter
    def redirect_url(self, redirect_url: str):
        """Sets the redirect_url of this QueryResponseV3.


        :param redirect_url: The redirect_url of this QueryResponseV3.
        :type redirect_url: str
        """

        self._redirect_url = redirect_url
