// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;
import java.util.Set;

@Entity
@Table(name = "attachment")
public class Attachment extends AuditEntity {

    @ManyToMany
    @JoinTable(name = "attachment_post_link", joinColumns = @JoinColumn(name = "post_id"), inverseJoinColumns = @JoinColumn(name = "attachment_id"))
    Set<Post> posts;

    @ManyToMany
    @JoinTable(name = "attachment_project_link", joinColumns = @JoinColumn(name = "project_id"), inverseJoinColumns = @JoinColumn(name = "attachment_id"))
    Set<Project> projects;

    @ManyToMany
    @JoinTable(name = "attachment_request_link", joinColumns = @JoinColumn(name = "request_id"), inverseJoinColumns = @JoinColumn(name = "attachment_id"))
    Set<Request> requests;

    @ManyToMany
    @JoinTable(name = "attachment_private_post_link", joinColumns = @JoinColumn(name = "post_id"), inverseJoinColumns = @JoinColumn(name = "attachment_id"))
    Set<Post> Posts;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    private String fileName;

    private String fileHash;

    private String fileSize;

    private String fileExtension;

    private String attachmentScope;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Attachment(fileName=" + this.getFileName() + ", fileHash=" + this.getFileHash() + ", fileSize=" + this.getFileSize() + ", fileExtension="
                + this.getFileExtension() + ", attachmentScope=" + this.getAttachmentScope() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Attachment() {
    }

    @java.lang.SuppressWarnings("all")
    public Attachment(final Set<Post> posts, final Set<Project> projects, final Set<Request> requests, final Set<Post> Posts, final Person createdBy,
            final Person modifiedBy, final String fileName, final String fileHash, final String fileSize, final String fileExtension,
            final String attachmentScope) {
        this.posts = posts;
        this.projects = projects;
        this.requests = requests;
        this.Posts = Posts;
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.fileName = fileName;
        this.fileHash = fileHash;
        this.fileSize = fileSize;
        this.fileExtension = fileExtension;
        this.attachmentScope = attachmentScope;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Post> getPosts() {
        return this.posts;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Project> getProjects() {
        return this.projects;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Request> getRequests() {
        return this.requests;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public String getFileName() {
        return this.fileName;
    }

    @java.lang.SuppressWarnings("all")
    public String getFileHash() {
        return this.fileHash;
    }

    @java.lang.SuppressWarnings("all")
    public String getFileSize() {
        return this.fileSize;
    }

    @java.lang.SuppressWarnings("all")
    public String getFileExtension() {
        return this.fileExtension;
    }

    @java.lang.SuppressWarnings("all")
    public String getAttachmentScope() {
        return this.attachmentScope;
    }

    @java.lang.SuppressWarnings("all")
    public void setPosts(final Set<Post> posts) {
        this.posts = posts;
    }

    @java.lang.SuppressWarnings("all")
    public void setProjects(final Set<Project> projects) {
        this.projects = projects;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequests(final Set<Request> requests) {
        this.requests = requests;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setFileName(final String fileName) {
        this.fileName = fileName;
    }

    @java.lang.SuppressWarnings("all")
    public void setFileHash(final String fileHash) {
        this.fileHash = fileHash;
    }

    @java.lang.SuppressWarnings("all")
    public void setFileSize(final String fileSize) {
        this.fileSize = fileSize;
    }

    @java.lang.SuppressWarnings("all")
    public void setFileExtension(final String fileExtension) {
        this.fileExtension = fileExtension;
    }

    @java.lang.SuppressWarnings("all")
    public void setAttachmentScope(final String attachmentScope) {
        this.attachmentScope = attachmentScope;
    }
}
