// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

@Entity(name = "Biobank")
@Table(name = "biobank")
public class Biobank extends BaseEntity {

    @ManyToMany(mappedBy = "biobanks")
    private Set<Person> persons = new HashSet<>();

    @ManyToMany(mappedBy = "biobanks")
    private Set<Network> networks = new HashSet<>();

    @ManyToMany(mappedBy = "biobanks")
    private Set<Query> queries = new HashSet<>();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "data_source_id")
    private DataSource dataSource;

    private String sourceId;

    private String name;

    @Lob
    @Column(columnDefinition = "VARCHAR(512)")
    private String description;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Biobank(sourceId=" + this.getSourceId() + ", name=" + this.getName() + ", description=" + this.getDescription() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Biobank() {
    }

    @java.lang.SuppressWarnings("all")
    public Biobank(final Set<Person> persons, final Set<Network> networks, final Set<Query> queries, final DataSource dataSource, final String sourceId,
            final String name, final String description) {
        this.persons = persons;
        this.networks = networks;
        this.queries = queries;
        this.dataSource = dataSource;
        this.sourceId = sourceId;
        this.name = name;
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Person> getPersons() {
        return this.persons;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Network> getNetworks() {
        return this.networks;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Query> getQueries() {
        return this.queries;
    }

    @java.lang.SuppressWarnings("all")
    public DataSource getDataSource() {
        return this.dataSource;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceId() {
        return this.sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public void setPersons(final Set<Person> persons) {
        this.persons = persons;
    }

    @java.lang.SuppressWarnings("all")
    public void setNetworks(final Set<Network> networks) {
        this.networks = networks;
    }

    @java.lang.SuppressWarnings("all")
    public void setQueries(final Set<Query> queries) {
        this.queries = queries;
    }

    @java.lang.SuppressWarnings("all")
    public void setDataSource(final DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @java.lang.SuppressWarnings("all")
    public void setSourceId(final String sourceId) {
        this.sourceId = sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }
}
