// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.sun.istack.NotNull;

import javax.persistence.*;

@Entity(name = "Collection")
@Table(name = "collection")
public class Collection extends BaseEntity {

    //  @ManyToMany(mappedBy = "collections")
    //  @Exclude
    //  private Set<Network> networks = new HashSet<>();
    //  @ManyToMany(mappedBy = "collections")
    //  @Exclude
    //  private Set<Person> persons = new HashSet<>();
    //  @ManyToMany(mappedBy = "collections")
    //  @Exclude
    //  private Set<Query> queries = new HashSet<>();
    //  @Id @GeneratedValue private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "data_source_id")
    @JsonIgnore
    private DataSource dataSource;

    //  @ManyToOne(fetch = FetchType.LAZY)
    //  @JoinColumn(name = "biobank_id")
    //  @NotNull
    //  @Exclude
    //  private Biobank biobank;
    @NotNull
    @Column(name = "source_id")
    private String sourceId;

    @NotNull
    private String name;

    private String description;

    @java.lang.SuppressWarnings("all")
    public Collection() {
    }

    @java.lang.SuppressWarnings("all")
    public Collection(final DataSource dataSource, final String sourceId, final String name, final String description) {
        this.dataSource = dataSource;
        this.sourceId = sourceId;
        this.name = name;
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public DataSource getDataSource() {
        return this.dataSource;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceId() {
        return this.sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @JsonIgnore
    @java.lang.SuppressWarnings("all")
    public void setDataSource(final DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @java.lang.SuppressWarnings("all")
    public void setSourceId(final String sourceId) {
        this.sourceId = sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }
}
