// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "form_field")
public class FormField extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "form_field_type_id")
    private FormFieldType formFieldType;

    private String name;

    private String label;

    private String category;

    private String defaultValue;

    @Column(name = "\"constraint\"")
    private String constraint;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "FormField(name=" + this.getName() + ", label=" + this.getLabel() + ", category=" + this.getCategory() + ", defaultValue="
                + this.getDefaultValue() + ", constraint=" + this.getConstraint() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public FormField() {
    }

    @java.lang.SuppressWarnings("all")
    public FormField(final Person createdBy, final Person modifiedBy, final FormFieldType formFieldType, final String name, final String label,
            final String category, final String defaultValue, final String constraint) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.formFieldType = formFieldType;
        this.name = name;
        this.label = label;
        this.category = category;
        this.defaultValue = defaultValue;
        this.constraint = constraint;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public FormFieldType getFormFieldType() {
        return this.formFieldType;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getLabel() {
        return this.label;
    }

    @java.lang.SuppressWarnings("all")
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    public String getDefaultValue() {
        return this.defaultValue;
    }

    @java.lang.SuppressWarnings("all")
    public String getConstraint() {
        return this.constraint;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setFormFieldType(final FormFieldType formFieldType) {
        this.formFieldType = formFieldType;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setLabel(final String label) {
        this.label = label;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    public void setDefaultValue(final String defaultValue) {
        this.defaultValue = defaultValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setConstraint(final String constraint) {
        this.constraint = constraint;
    }
}
