// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "form_field_type")
public class FormFieldType extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "form_type_option_id")
    private FormTypeOption formTypeOption;

    private String type;

    private String validation;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "FormFieldType(type=" + this.getType() + ", validation=" + this.getValidation() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public FormFieldType() {
    }

    @java.lang.SuppressWarnings("all")
    public FormFieldType(final Person createdBy, final Person modifiedBy, final FormTypeOption formTypeOption, final String type, final String validation) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.formTypeOption = formTypeOption;
        this.type = type;
        this.validation = validation;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public FormTypeOption getFormTypeOption() {
        return this.formTypeOption;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public String getValidation() {
        return this.validation;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setFormTypeOption(final FormTypeOption formTypeOption) {
        this.formTypeOption = formTypeOption;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setValidation(final String validation) {
        this.validation = validation;
    }
}
