// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "form_field_value")
public class FormFieldValue extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "form_request_field_id")
    private FormRequestField formRequestField;

    private String value;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "FormFieldValue(value=" + this.getValue() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public FormFieldValue() {
    }

    @java.lang.SuppressWarnings("all")
    public FormFieldValue(final Person createdBy, final Person modifiedBy, final FormRequestField formRequestField, final String value) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.formRequestField = formRequestField;
        this.value = value;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public FormRequestField getFormRequestField() {
        return this.formRequestField;
    }

    @java.lang.SuppressWarnings("all")
    public String getValue() {
        return this.value;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setFormRequestField(final FormRequestField formRequestField) {
        this.formRequestField = formRequestField;
    }

    @java.lang.SuppressWarnings("all")
    public void setValue(final String value) {
        this.value = value;
    }
}
