// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "form_field_selection")
public class FormFieldSelection extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "form_template_id")
    private FormTemplate formTemplate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "form_field_id")
    private FormField formField;

    @Column(name = "\"order\"")
    private Integer order;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "FormFieldSelection(order=" + this.getOrder() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public FormFieldSelection() {
    }

    @java.lang.SuppressWarnings("all")
    public FormFieldSelection(final Person createdBy, final Person modifiedBy, final FormTemplate formTemplate, final FormField formField,
            final Integer order) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.formTemplate = formTemplate;
        this.formField = formField;
        this.order = order;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public FormTemplate getFormTemplate() {
        return this.formTemplate;
    }

    @java.lang.SuppressWarnings("all")
    public FormField getFormField() {
        return this.formField;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getOrder() {
        return this.order;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setFormTemplate(final FormTemplate formTemplate) {
        this.formTemplate = formTemplate;
    }

    @java.lang.SuppressWarnings("all")
    public void setFormField(final FormField formField) {
        this.formField = formField;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrder(final Integer order) {
        this.order = order;
    }
}
