// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "form_template")
public class FormTemplate extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "biobank_id")
    private Biobank biobank;

    private Boolean commercial;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "FormTemplate(commercial=" + this.getCommercial() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public FormTemplate() {
    }

    @java.lang.SuppressWarnings("all")
    public FormTemplate(final Person createdBy, final Person modifiedBy, final Biobank biobank, final Boolean commercial) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.biobank = biobank;
        this.commercial = commercial;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public Biobank getBiobank() {
        return this.biobank;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getCommercial() {
        return this.commercial;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setBiobank(final Biobank biobank) {
        this.biobank = biobank;
    }

    @java.lang.SuppressWarnings("all")
    public void setCommercial(final Boolean commercial) {
        this.commercial = commercial;
    }
}
