// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "lifecycle_request_collection_status")
public class LifecycleRequestCollectionStatus extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "request_id")
    private Request request;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "collection_id")
    private Collection collection;

    private String status;

    private String statusType;

    private Date statusDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status_by")
    private Person Person;

    // TODO: should this one be Json instead of txt blob?
    @Lob
    private String statusJson;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LifecycleRequestCollectionStatus(status=" + this.getStatus() + ", statusType=" + this.getStatusType() + ", statusDate=" + this.getStatusDate()
                + ", statusJson=" + this.getStatusJson() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public LifecycleRequestCollectionStatus() {
    }

    @java.lang.SuppressWarnings("all")
    public LifecycleRequestCollectionStatus(final Person createdBy, final Person modifiedBy, final Request request, final Collection collection,
            final String status, final String statusType, final Date statusDate, final Person Person, final String statusJson) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.request = request;
        this.collection = collection;
        this.status = status;
        this.statusType = statusType;
        this.statusDate = statusDate;
        this.Person = Person;
        this.statusJson = statusJson;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public Request getRequest() {
        return this.request;
    }

    @java.lang.SuppressWarnings("all")
    public Collection getCollection() {
        return this.collection;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatusType() {
        return this.statusType;
    }

    @java.lang.SuppressWarnings("all")
    public Date getStatusDate() {
        return this.statusDate;
    }

    @java.lang.SuppressWarnings("all")
    public Person getPerson() {
        return this.Person;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatusJson() {
        return this.statusJson;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequest(final Request request) {
        this.request = request;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollection(final Collection collection) {
        this.collection = collection;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatusType(final String statusType) {
        this.statusType = statusType;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatusDate(final Date statusDate) {
        this.statusDate = statusDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setPerson(final Person Person) {
        this.Person = Person;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatusJson(final String statusJson) {
        this.statusJson = statusJson;
    }
}
