// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

@Entity(name = "Network")
@Table(name = "network")
public class Network extends BaseEntity {

    @ManyToMany
    @JoinTable(name = "network_biobank_link", joinColumns = { @JoinColumn(name = "biobank_id") }, inverseJoinColumns = { @JoinColumn(name = "network_id") })
    Set<Biobank> biobanks = new HashSet<>();

    @ManyToMany
    @JoinTable(name = "network_collection_link", joinColumns = { @JoinColumn(name = "collection_id") }, inverseJoinColumns = { @JoinColumn(name = "network_id") })
    Set<Collection> collections = new HashSet<>();

    @ManyToMany(mappedBy = "networks")
    private Set<Person> persons;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "data_source_id")
    private DataSource datasource;

    private String sourceId;

    private String name;

    private String acronym;

    @Lob
    @Column(columnDefinition = "VARCHAR(512)")
    private String description;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Network(sourceId=" + this.getSourceId() + ", name=" + this.getName() + ", acronym=" + this.getAcronym() + ", description="
                + this.getDescription() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Network() {
    }

    @java.lang.SuppressWarnings("all")
    public Network(final Set<Biobank> biobanks, final Set<Collection> collections, final Set<Person> persons, final DataSource datasource,
            final String sourceId, final String name, final String acronym, final String description) {
        this.biobanks = biobanks;
        this.collections = collections;
        this.persons = persons;
        this.datasource = datasource;
        this.sourceId = sourceId;
        this.name = name;
        this.acronym = acronym;
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Biobank> getBiobanks() {
        return this.biobanks;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Collection> getCollections() {
        return this.collections;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Person> getPersons() {
        return this.persons;
    }

    @java.lang.SuppressWarnings("all")
    public DataSource getDatasource() {
        return this.datasource;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceId() {
        return this.sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getAcronym() {
        return this.acronym;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public void setBiobanks(final Set<Biobank> biobanks) {
        this.biobanks = biobanks;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollections(final Set<Collection> collections) {
        this.collections = collections;
    }

    @java.lang.SuppressWarnings("all")
    public void setPersons(final Set<Person> persons) {
        this.persons = persons;
    }

    @java.lang.SuppressWarnings("all")
    public void setDatasource(final DataSource datasource) {
        this.datasource = datasource;
    }

    @java.lang.SuppressWarnings("all")
    public void setSourceId(final String sourceId) {
        this.sourceId = sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setAcronym(final String acronym) {
        this.acronym = acronym;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }
}
