// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "notification_settings")
public class NotificationSettings extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "person_id")
    private Person person;

    private String notificationType;

    private String sendSetting;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "NotificationSettings(notificationType=" + this.getNotificationType() + ", sendSetting=" + this.getSendSetting() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public NotificationSettings() {
    }

    @java.lang.SuppressWarnings("all")
    public NotificationSettings(final Person createdBy, final Person modifiedBy, final Person person, final String notificationType, final String sendSetting) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.person = person;
        this.notificationType = notificationType;
        this.sendSetting = sendSetting;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getPerson() {
        return this.person;
    }

    @java.lang.SuppressWarnings("all")
    public String getNotificationType() {
        return this.notificationType;
    }

    @java.lang.SuppressWarnings("all")
    public String getSendSetting() {
        return this.sendSetting;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setPerson(final Person person) {
        this.person = person;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotificationType(final String notificationType) {
        this.notificationType = notificationType;
    }

    @java.lang.SuppressWarnings("all")
    public void setSendSetting(final String sendSetting) {
        this.sendSetting = sendSetting;
    }
}
