// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "notification_mail")
public class NotificationMail extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "notification_id")
    private Notification notification;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recipient_id")
    private Person person;

    private String emailAddress;

    private String sendStatus;

    private Date sendDate;

    private String subject;

    @Lob
    private String body;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "NotificationMail(emailAddress=" + this.getEmailAddress() + ", sendStatus=" + this.getSendStatus() + ", sendDate=" + this.getSendDate()
                + ", subject=" + this.getSubject() + ", body=" + this.getBody() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public NotificationMail() {
    }

    @java.lang.SuppressWarnings("all")
    public NotificationMail(final Person createdBy, final Person modifiedBy, final Notification notification, final Person person, final String emailAddress,
            final String sendStatus, final Date sendDate, final String subject, final String body) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.notification = notification;
        this.person = person;
        this.emailAddress = emailAddress;
        this.sendStatus = sendStatus;
        this.sendDate = sendDate;
        this.subject = subject;
        this.body = body;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public Notification getNotification() {
        return this.notification;
    }

    @java.lang.SuppressWarnings("all")
    public Person getPerson() {
        return this.person;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmailAddress() {
        return this.emailAddress;
    }

    @java.lang.SuppressWarnings("all")
    public String getSendStatus() {
        return this.sendStatus;
    }

    @java.lang.SuppressWarnings("all")
    public Date getSendDate() {
        return this.sendDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubject() {
        return this.subject;
    }

    @java.lang.SuppressWarnings("all")
    public String getBody() {
        return this.body;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotification(final Notification notification) {
        this.notification = notification;
    }

    @java.lang.SuppressWarnings("all")
    public void setPerson(final Person person) {
        this.person = person;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmailAddress(final String emailAddress) {
        this.emailAddress = emailAddress;
    }

    @java.lang.SuppressWarnings("all")
    public void setSendStatus(final String sendStatus) {
        this.sendStatus = sendStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setSendDate(final Date sendDate) {
        this.sendDate = sendDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubject(final String subject) {
        this.subject = subject;
    }

    @java.lang.SuppressWarnings("all")
    public void setBody(final String body) {
        this.body = body;
    }
}
