// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "notification")
public class Notification extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "request_id")
    private Request request;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id")
    private Person sender;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_id")
    private Post post;

    private String notificationType;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Notification(notificationType=" + this.getNotificationType() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Notification() {
    }

    @java.lang.SuppressWarnings("all")
    public Notification(final Person createdBy, final Person modifiedBy, final Request request, final Person sender, final Post post,
            final String notificationType) {
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.request = request;
        this.sender = sender;
        this.post = post;
        this.notificationType = notificationType;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public Request getRequest() {
        return this.request;
    }

    @java.lang.SuppressWarnings("all")
    public Person getSender() {
        return this.sender;
    }

    @java.lang.SuppressWarnings("all")
    public Post getPost() {
        return this.post;
    }

    @java.lang.SuppressWarnings("all")
    public String getNotificationType() {
        return this.notificationType;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequest(final Request request) {
        this.request = request;
    }

    @java.lang.SuppressWarnings("all")
    public void setSender(final Person sender) {
        this.sender = sender;
    }

    @java.lang.SuppressWarnings("all")
    public void setPost(final Post post) {
        this.post = post;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotificationType(final String notificationType) {
        this.notificationType = notificationType;
    }
}
