// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "person_request_link")
public class PersonRequestLink extends AuditEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "person_id")
    private Person person;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "request_id")
    private Request request;

    private Integer roleId;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PersonRequestLink(roleId=" + this.getRoleId() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public PersonRequestLink() {
    }

    @java.lang.SuppressWarnings("all")
    public PersonRequestLink(final Person person, final Request request, final Integer roleId) {
        this.person = person;
        this.request = request;
        this.roleId = roleId;
    }

    @java.lang.SuppressWarnings("all")
    public Person getPerson() {
        return this.person;
    }

    @java.lang.SuppressWarnings("all")
    public Request getRequest() {
        return this.request;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getRoleId() {
        return this.roleId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPerson(final Person person) {
        this.person = person;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequest(final Request request) {
        this.request = request;
    }

    @java.lang.SuppressWarnings("all")
    public void setRoleId(final Integer roleId) {
        this.roleId = roleId;
    }
}
