// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

@Entity
@Table(name = "post")
public class Post extends AuditEntity {

    @ManyToMany(mappedBy = "posts")
    Set<Attachment> attachments;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", insertable = false, updatable = false)
    private Person createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by", insertable = false, updatable = false)
    private Person modifiedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "request_id")
    private Request request;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "poster_id")
    private Person poster;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "biobank_id")
    private Biobank biobank;

    @Lob
    private String postText;

    private String postStatus;

    private Date postDate;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Post(postText=" + this.getPostText() + ", postStatus=" + this.getPostStatus() + ", postDate=" + this.getPostDate() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Post() {
    }

    @java.lang.SuppressWarnings("all")
    public Post(final Set<Attachment> attachments, final Person createdBy, final Person modifiedBy, final Request request, final Person poster,
            final Biobank biobank, final String postText, final String postStatus, final Date postDate) {
        this.attachments = attachments;
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.request = request;
        this.poster = poster;
        this.biobank = biobank;
        this.postText = postText;
        this.postStatus = postStatus;
        this.postDate = postDate;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Attachment> getAttachments() {
        return this.attachments;
    }

    @java.lang.SuppressWarnings("all")
    public Person getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public Person getModifiedBy() {
        return this.modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public Request getRequest() {
        return this.request;
    }

    @java.lang.SuppressWarnings("all")
    public Person getPoster() {
        return this.poster;
    }

    @java.lang.SuppressWarnings("all")
    public Biobank getBiobank() {
        return this.biobank;
    }

    @java.lang.SuppressWarnings("all")
    public String getPostText() {
        return this.postText;
    }

    @java.lang.SuppressWarnings("all")
    public String getPostStatus() {
        return this.postStatus;
    }

    @java.lang.SuppressWarnings("all")
    public Date getPostDate() {
        return this.postDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setAttachments(final Set<Attachment> attachments) {
        this.attachments = attachments;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedBy(final Person createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setModifiedBy(final Person modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequest(final Request request) {
        this.request = request;
    }

    @java.lang.SuppressWarnings("all")
    public void setPoster(final Person poster) {
        this.poster = poster;
    }

    @java.lang.SuppressWarnings("all")
    public void setBiobank(final Biobank biobank) {
        this.biobank = biobank;
    }

    @java.lang.SuppressWarnings("all")
    public void setPostText(final String postText) {
        this.postText = postText;
    }

    @java.lang.SuppressWarnings("all")
    public void setPostStatus(final String postStatus) {
        this.postStatus = postStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setPostDate(final Date postDate) {
        this.postDate = postDate;
    }
}
