// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;
import java.util.Set;

@Entity
@Table(name = "request")
public class Request extends AuditEntity {

    @ManyToMany(mappedBy = "requests")
    Set<Attachment> attachments;

    private String title;

    @Lob
    private String requestDescription;

    @Lob
    private String ethicsVote;

    private Boolean testRequest;

    private String requestToken;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id")
    private Project project;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Request(title=" + this.getTitle() + ", requestDescription=" + this.getRequestDescription() + ", ethicsVote=" + this.getEthicsVote()
                + ", testRequest=" + this.getTestRequest() + ", requestToken=" + this.getRequestToken() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Request() {
    }

    @java.lang.SuppressWarnings("all")
    public Request(final Set<Attachment> attachments, final String title, final String requestDescription, final String ethicsVote, final Boolean testRequest,
            final String requestToken, final Project project) {
        this.attachments = attachments;
        this.title = title;
        this.requestDescription = requestDescription;
        this.ethicsVote = ethicsVote;
        this.testRequest = testRequest;
        this.requestToken = requestToken;
        this.project = project;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Attachment> getAttachments() {
        return this.attachments;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getRequestDescription() {
        return this.requestDescription;
    }

    @java.lang.SuppressWarnings("all")
    public String getEthicsVote() {
        return this.ethicsVote;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getTestRequest() {
        return this.testRequest;
    }

    @java.lang.SuppressWarnings("all")
    public String getRequestToken() {
        return this.requestToken;
    }

    @java.lang.SuppressWarnings("all")
    public Project getProject() {
        return this.project;
    }

    @java.lang.SuppressWarnings("all")
    public void setAttachments(final Set<Attachment> attachments) {
        this.attachments = attachments;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequestDescription(final String requestDescription) {
        this.requestDescription = requestDescription;
    }

    @java.lang.SuppressWarnings("all")
    public void setEthicsVote(final String ethicsVote) {
        this.ethicsVote = ethicsVote;
    }

    @java.lang.SuppressWarnings("all")
    public void setTestRequest(final Boolean testRequest) {
        this.testRequest = testRequest;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequestToken(final String requestToken) {
        this.requestToken = requestToken;
    }

    @java.lang.SuppressWarnings("all")
    public void setProject(final Project project) {
        this.project = project;
    }
    //    @OneToMany(
    //            mappedBy = "requestToken",
    //            fetch = FetchType.EAGER,
    //            cascade = CascadeType.ALL,
    //            orphanRemoval = false
    //    )
    //    private List<RequestQuery> requestQueries = new ArrayList<>();
    //
    //    @OneToMany(
    //            mappedBy = "requestId",
    //            fetch = FetchType.EAGER,
    //            cascade = CascadeType.ALL
    //    )
    //    private List<FormTemplate> formTemplates = new ArrayList<>();
}
