// Generated by delombok at Wed May 04 16:43:34 CEST 2022
package eu.bbmri.eric.csit.service.model;

import javax.persistence.*;

@Entity
@Table(name = "role")
public class Role extends AuditEntity {

    private String name;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "role_id", insertable = false, updatable = false)
    private PersonProjectLink personProjectLink;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "role_id", insertable = false, updatable = false)
    private PersonRequestLink personRequestLink;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Role(name=" + this.getName() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Role() {
    }

    @java.lang.SuppressWarnings("all")
    public Role(final String name, final PersonProjectLink personProjectLink, final PersonRequestLink personRequestLink) {
        this.name = name;
        this.personProjectLink = personProjectLink;
        this.personRequestLink = personRequestLink;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public PersonProjectLink getPersonProjectLink() {
        return this.personProjectLink;
    }

    @java.lang.SuppressWarnings("all")
    public PersonRequestLink getPersonRequestLink() {
        return this.personRequestLink;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setPersonProjectLink(final PersonProjectLink personProjectLink) {
        this.personProjectLink = personProjectLink;
    }

    @java.lang.SuppressWarnings("all")
    public void setPersonRequestLink(final PersonRequestLink personRequestLink) {
        this.personRequestLink = personRequestLink;
    }
}
